- name: Backup Current Configuration for "{{ inventory_hostname }}"
  vyos_config:
    backup: yes
    provider: "{{ creds }}"

# Single interface tasks
- name: Delete an existing default route configuration
  vyos_static_route:
    prefix: 0.0.0.0/0
    next_hop: "{{ vyos_static_route_nxt_hop }}"
    state: absent
    provider: "{{ creds }}"
  when: (vyos_static_route_w_clear == 'enabled' and vyos_static_default == 'enabled' and vyos_static_route_agg == 'disabled')

- name: Configure a static default route
  vyos_static_route:
    prefix: 0.0.0.0/0
    next_hop: "{{ vyos_static_route_nxt_hop }}"
    state: present
    provider: "{{ creds }}"
  when: (vyos_static_route_build == 'enabled' and vyos_static_default == 'enabled' and vyos_static_route_agg == 'disabled')

- name: Delete an existing static route configuration for {{ vyos_static_route_dest }}
  vyos_static_route:
    prefix: "{{ vyos_static_route_dest }}"
    next_hop: "{{ vyos_static_route_nxt_hop }}"
    state: absent
    provider: "{{ creds }}"
  when: (vyos_static_route_w_clear == 'enabled' and vyos_static_route_agg == 'disabled')

- name: Configure a static route configuration for {{ vyos_static_route_dest }}
  vyos_static_route:
    prefix: "{{ vyos_static_route_dest }}"
    next_hop: "{{ vyos_static_route_nxt_hop }}"
    state: present
    provider: "{{ creds }}"
  when: (vyos_static_route_build == 'enabled' and vyos_static_route_agg == 'disabled')

- name: Equivalent in set syntax command
  debug: msg="{{ set_syntax_static }}"
  when: (vyos_static_route_build == 'enabled' and vyos_static_route_agg == 'disabled')

# Aggregate tasks
- name: Multiple interface Addition variables 
  include_vars: vars/task_vars/vy_static_aggregate.yml
  when: vyos_static_route_agg == 'enabled'

- name: Aggregate clear routes
  vyos_static_route:
    aggregate:
      - { prefix: "{{ agg_vyos_static_prefix1 }}", next_hop: "{{ agg_vyos_static_nxt_hop1 }}"}
      - { prefix: "{{ agg_vyos_static_prefix2 }}", next_hop: "{{ agg_vyos_static_nxt_hop2 }}"}
    state: absent
    provider: "{{ creds }}"
  when: (vyos_static_route_agg == 'enabled' and agg_vyos_static_w_clear == 'enabled')

- name: Aggregate add routes
  vyos_static_route:
    aggregate:
      - { prefix: "{{ agg_vyos_static_prefix1 }}", next_hop: "{{ agg_vyos_static_nxt_hop1 }}"}
      - { prefix: "{{ agg_vyos_static_prefix2 }}", next_hop: "{{ agg_vyos_static_nxt_hop2 }}"}
    state: present
    provider: "{{ creds }}"
  when: (vyos_static_route_agg == 'enabled' and agg_vyos_static_build == 'enabled')

- name: Aggregate Equivalent in set syntax command
  debug: msg="{{ agg_set_syntax_static }}"
  when: (vyos_static_route_agg == 'enabled' and agg_vyos_static_build == 'enabled')

- name: Commit and save changes for {{ inventory_hostname }}
  vyos_config:
    save: yes
    provider: "{{ creds }}"
